testfiles:
	cd ./Silicon_1600K_classical && anharmonic_free_energy --temperature 1600 -qg3ph 10 10 10 -qg4ph 10 10 10 -qgh 30 30 30
	cd ./Neon_14K_quantum && anharmonic_free_energy --temperature 14 --quantum -qg3ph 10 10 10 -qg4ph 10 10 10 -qgh 30 30 30
